[2025-05-31T19:25:42.671+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: real_estate_pipeline.train_model manual__2025-05-31T19:25:25+00:00 [queued]>
[2025-05-31T19:25:42.697+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: real_estate_pipeline.train_model manual__2025-05-31T19:25:25+00:00 [queued]>
[2025-05-31T19:25:42.698+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2025-05-31T19:25:42.729+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): train_model> on 2025-05-31 19:25:25+00:00
[2025-05-31T19:25:42.753+0000] {standard_task_runner.py:60} INFO - Started process 483 to run task
[2025-05-31T19:25:42.768+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'real_estate_pipeline', 'train_model', 'manual__2025-05-31T19:25:25+00:00', '--job-id', '21', '--raw', '--subdir', 'DAGS_FOLDER/real_estate_pipeline.py', '--cfg-path', '/tmp/tmpjvcug5eg']
[2025-05-31T19:25:42.773+0000] {standard_task_runner.py:88} INFO - Job 21: Subtask train_model
[2025-05-31T19:25:42.816+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-05-31T19:25:42.914+0000] {task_command.py:423} INFO - Running <TaskInstance: real_estate_pipeline.train_model manual__2025-05-31T19:25:25+00:00 [running]> on host 279fe042b4ac
[2025-05-31T19:25:43.272+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='real_estate_pipeline' AIRFLOW_CTX_TASK_ID='train_model' AIRFLOW_CTX_EXECUTION_DATE='2025-05-31T19:25:25+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-05-31T19:25:25+00:00'
[2025-05-31T19:25:43.278+0000] {train.py:55} INFO - Iniciando entrenamiento del modelo...
[2025-05-31T19:25:43.410+0000] {train.py:86} INFO - R2 Score: -0.021116482857372887
[2025-05-31T19:25:43.990+0000] {logging_mixin.py:188} WARNING - 2025/05/31 19:25:43 WARNING mlflow.utils.git_utils: Failed to import Git (the Git executable is probably not on your PATH), so Git SHA is not available. Error: Failed to initialize: Bad git executable.
The git executable must be specified in one of the following ways:
    - be included in your $PATH
    - be set via $GIT_PYTHON_GIT_EXECUTABLE
    - explicitly set via git.refresh(<full-path-to-git-executable>)

All git commands will error until this is rectified.

This initial message can be silenced or aggravated in the future by setting the
$GIT_PYTHON_REFRESH environment variable. Use one of the following values:
    - quiet|q|silence|s|silent|none|n|0: for no message or exception
    - warn|w|warning|log|l|1: for a warning message (logging level CRITICAL, displayed by default)
    - error|e|exception|raise|r|2: for a raised exception

Example:
    export GIT_PYTHON_REFRESH=quiet
[2025-05-31T19:25:51.820+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.8/site-packages/_distutils_hack/__init__.py:33 UserWarning: Setuptools is replacing distutils.
[2025-05-31T19:25:52.191+0000] {credentials.py:1147} INFO - Found credentials in environment variables.
[2025-05-31T19:25:52.785+0000] {python.py:201} INFO - Done. Returned value was: -0.021116482857372887
[2025-05-31T19:25:52.909+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=real_estate_pipeline, task_id=train_model, execution_date=20250531T192525, start_date=20250531T192542, end_date=20250531T192552
[2025-05-31T19:25:53.101+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-05-31T19:25:53.175+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
